---
- name: check if podman binary is present
  stat:
    path: /usr/bin/podman
  register: podman_binary

- name: set_fact container_binary
  set_fact:
    container_binary: "{{ 'podman' if podman_binary.stat.exists else 'docker' }}"
  when: not docker2podman | default(false) | bool
